apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector:
    app: web
  ports:
  - name: nginx-custom
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort